//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_project.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitness_project.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIPTIONS LIST.
        /// </summary>
        public static string btnActiveSub {
            get {
                return ResourceManager.GetString("btnActiveSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Person.
        /// </summary>
        public static string btnAddPeson {
            get {
                return ResourceManager.GetString("btnAddPeson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDIT.
        /// </summary>
        public static string btnAudit {
            get {
                return ResourceManager.GetString("btnAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string btnCategories {
            get {
                return ResourceManager.GetString("btnCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES LIST.
        /// </summary>
        public static string btnCatLIst {
            get {
                return ResourceManager.GetString("btnCatLIst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string btnExist {
            get {
                return ResourceManager.GetString("btnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBERS LIST.
        /// </summary>
        public static string btnMemberList {
            get {
                return ResourceManager.GetString("btnMemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBERS.
        /// </summary>
        public static string btnMembers {
            get {
                return ResourceManager.GetString("btnMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIPTIONS.
        /// </summary>
        public static string btnSubscripton {
            get {
                return ResourceManager.GetString("btnSubscripton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAINERS LIST.
        /// </summary>
        public static string btnTrainerList {
            get {
                return ResourceManager.GetString("btnTrainerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAINERS.
        /// </summary>
        public static string btnTrainers {
            get {
                return ResourceManager.GetString("btnTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS.
        /// </summary>
        public static string btnUsers {
            get {
                return ResourceManager.GetString("btnUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS LIST.
        /// </summary>
        public static string btnUsersList {
            get {
                return ResourceManager.GetString("btnUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND.
        /// </summary>
        public static string buttonFind {
            get {
                return ResourceManager.GetString("buttonFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        public static string Cancelledtitle {
            get {
                return ResourceManager.GetString("Cancelledtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Audit tab.
        /// </summary>
        public static string chbAuditTab {
            get {
                return ResourceManager.GetString("chbAuditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Categories tab.
        /// </summary>
        public static string chbCategoriesTab {
            get {
                return ResourceManager.GetString("chbCategoriesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full access.
        /// </summary>
        public static string chbfullAccess {
            get {
                return ResourceManager.GetString("chbfullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Members tab.
        /// </summary>
        public static string chbMembersTab {
            get {
                return ResourceManager.GetString("chbMembersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Subscriptions tab.
        /// </summary>
        public static string chbSubscriptionsTab {
            get {
                return ResourceManager.GetString("chbSubscriptionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Trainers tab.
        /// </summary>
        public static string chbTrainersTab {
            get {
                return ResourceManager.GetString("chbTrainersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Users tab.
        /// </summary>
        public static string chbUsersTab {
            get {
                return ResourceManager.GetString("chbUsersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string deniedTitle {
            get {
                return ResourceManager.GetString("deniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string FilterById {
            get {
                return ResourceManager.GetString("FilterById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FilterByName {
            get {
                return ResourceManager.GetString("FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string gbFilter {
            get {
                return ResourceManager.GetString("gbFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER PERMISSION.
        /// </summary>
        public static string gbPermission {
            get {
                return ResourceManager.GetString("gbPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please insert a valid input..
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string InvalidInputTitle {
            get {
                return ResourceManager.GetString("InvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person not found. Please insert a valid value.
        /// </summary>
        public static string InvalidPersonInput {
            get {
                return ResourceManager.GetString("InvalidPersonInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW CATEGORY.
        /// </summary>
        public static string lblAddCatTitle {
            get {
                return ResourceManager.GetString("lblAddCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW MEMBER.
        /// </summary>
        public static string lblAddNewMember {
            get {
                return ResourceManager.GetString("lblAddNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SUBSCRIPTION SCREEN.
        /// </summary>
        public static string lblAddNewSub {
            get {
                return ResourceManager.GetString("lblAddNewSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW TRAINER.
        /// </summary>
        public static string lblAddNewTrainer {
            get {
                return ResourceManager.GetString("lblAddNewTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW USER.
        /// </summary>
        public static string lblAddNewUser {
            get {
                return ResourceManager.GetString("lblAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL APPLICANTS.
        /// </summary>
        public static string lblAppCount {
            get {
                return ResourceManager.GetString("lblAppCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDIT SCREEN.
        /// </summary>
        public static string lblAuditTitle {
            get {
                return ResourceManager.GetString("lblAuditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        public static string LblCategory {
            get {
                return ResourceManager.GetString("LblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id.
        /// </summary>
        public static string lblCategoryId {
            get {
                return ResourceManager.GetString("lblCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNT.
        /// </summary>
        public static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END DATE.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEES.
        /// </summary>
        public static string lblFees {
            get {
                return ResourceManager.GetString("lblFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL FEES.
        /// </summary>
        public static string lblfees1 {
            get {
                return ResourceManager.GetString("lblfees1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string lblFind {
            get {
                return ResourceManager.GetString("lblFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND SUBSCRIPTIONJ SCREEN.
        /// </summary>
        public static string lblFindSubTitle {
            get {
                return ResourceManager.GetString("lblFindSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER NAME.
        /// </summary>
        public static string lblMemberName {
            get {
                return ResourceManager.GetString("lblMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTH.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIPTION DURATION.
        /// </summary>
        public static string lblMonthDuration {
            get {
                return ResourceManager.GetString("lblMonthDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string lblNoData {
            get {
                return ResourceManager.GetString("lblNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person ID.
        /// </summary>
        public static string lblPersonId {
            get {
                return ResourceManager.GetString("lblPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string lblSalary {
            get {
                return ResourceManager.GetString("lblSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        public static string lblSearchBy {
            get {
                return ResourceManager.GetString("lblSearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string lblSecondName {
            get {
                return ResourceManager.GetString("lblSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string lblSelectCategory {
            get {
                return ResourceManager.GetString("lblSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGROY INFO SCREEN.
        /// </summary>
        public static string lblShowCatTitle {
            get {
                return ResourceManager.GetString("lblShowCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Info.
        /// </summary>
        public static string lblShowMemberTitle {
            get {
                return ResourceManager.GetString("lblShowMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Info.
        /// </summary>
        public static string lblShowTrainerInfo {
            get {
                return ResourceManager.GetString("lblShowTrainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        public static string lblShowUserInfo {
            get {
                return ResourceManager.GetString("lblShowUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string lblSortBy {
            get {
                return ResourceManager.GetString("lblSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START DATE.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL SUBSCRIPTIONS.
        /// </summary>
        public static string lbltotalSub {
            get {
                return ResourceManager.GetString("lbltotalSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer&apos;s Categories.
        /// </summary>
        public static string lblTrainerCategories {
            get {
                return ResourceManager.GetString("lblTrainerCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAINER NAME.
        /// </summary>
        public static string lblTrainerName {
            get {
                return ResourceManager.GetString("lblTrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains.
        /// </summary>
        public static string lblTrains {
            get {
                return ResourceManager.GetString("lblTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CATEGORY SCREEN.
        /// </summary>
        public static string lblUpdateCatTitle {
            get {
                return ResourceManager.GetString("lblUpdateCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Password.
        /// </summary>
        public static string lblValidatePassword {
            get {
                return ResourceManager.GetString("lblValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exist.
        /// </summary>
        public static string messageCatExist {
            get {
                return ResourceManager.GetString("messageCatExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid numeric ID..
        /// </summary>
        public static string messageInvalidNumeric {
            get {
                return ResourceManager.GetString("messageInvalidNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exist.
        /// </summary>
        public static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselected row.
        /// </summary>
        public static string NoSelectedRowTitle {
            get {
                return ResourceManager.GetString("NoSelectedRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person added successfully.
        /// </summary>
        public static string PersonAddSuc {
            get {
                return ResourceManager.GetString("PersonAddSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string rbFemale {
            get {
                return ResourceManager.GetString("rbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string rbMale {
            get {
                return ResourceManager.GetString("rbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are required..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this information?.
        /// </summary>
        public static string rjAskToSaveUser {
            get {
                return ResourceManager.GetString("rjAskToSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one permission to the user..
        /// </summary>
        public static string rjAssingOneAtLeast {
            get {
                return ResourceManager.GetString("rjAssingOneAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation password does not match the original password..
        /// </summary>
        public static string rjConvfimPasswordNotMatch {
            get {
                return ResourceManager.GetString("rjConvfimPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PERSON INFO.
        /// </summary>
        public static string rjEditPersonlalbel {
            get {
                return ResourceManager.GetString("rjEditPersonlalbel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to the {0} tab. Please contact the administrator..
        /// </summary>
        public static string rjMessageDenied {
            get {
                return ResourceManager.GetString("rjMessageDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please insert a valid input..
        /// </summary>
        public static string rjNotValidInput {
            get {
                return ResourceManager.GetString("rjNotValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer not found. Please insert a valid value..
        /// </summary>
        public static string rjNotValidTrainer {
            get {
                return ResourceManager.GetString("rjNotValidTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person already has an active subscription in this category..
        /// </summary>
        public static string rjPersonSubToCat {
            get {
                return ResourceManager.GetString("rjPersonSubToCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal cancelled..
        /// </summary>
        public static string rjRenewCancelled {
            get {
                return ResourceManager.GetString("rjRenewCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription renewed for {0} month.
        /// </summary>
        public static string rjRenewDone {
            get {
                return ResourceManager.GetString("rjRenewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill required field before searching..
        /// </summary>
        public static string rjRquiredTextBox {
            get {
                return ResourceManager.GetString("rjRquiredTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information has been saved successfully..
        /// </summary>
        public static string rjSaveUser {
            get {
                return ResourceManager.GetString("rjSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row.
        /// </summary>
        public static string rjSelectRow {
            get {
                return ResourceManager.GetString("rjSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription added successfully..
        /// </summary>
        public static string rjSubAdded {
            get {
                return ResourceManager.GetString("rjSubAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription not found. Please insert a valid value.
        /// </summary>
        public static string rjSubNotFound {
            get {
                return ResourceManager.GetString("rjSubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription already renewed..
        /// </summary>
        public static string rjSubRenewed {
            get {
                return ResourceManager.GetString("rjSubRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer not assigned to any category yet.
        /// </summary>
        public static string rjTrainerNotAssignToCategory {
            get {
                return ResourceManager.GetString("rjTrainerNotAssignToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user already exists for the selected person ID..
        /// </summary>
        public static string rjUserExist {
            get {
                return ResourceManager.GetString("rjUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found. Please insert a valid value.
        /// </summary>
        public static string rjUserNotFound {
            get {
                return ResourceManager.GetString("rjUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save a new person?.
        /// </summary>
        public static string SavePerson {
            get {
                return ResourceManager.GetString("SavePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string TabAudit {
            get {
                return ResourceManager.GetString("TabAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TabCategory {
            get {
                return ResourceManager.GetString("TabCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string TabMembers {
            get {
                return ResourceManager.GetString("TabMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string TabSubsc {
            get {
                return ResourceManager.GetString("TabSubsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainers.
        /// </summary>
        public static string TabTrainers {
            get {
                return ResourceManager.GetString("TabTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string TabUsers {
            get {
                return ResourceManager.GetString("TabUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Info.
        /// </summary>
        public static string tbPersonInfo {
            get {
                return ResourceManager.GetString("tbPersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Info.
        /// </summary>
        public static string tbSubInfo {
            get {
                return ResourceManager.GetString("tbSubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Info.
        /// </summary>
        public static string tbTrainerInfo {
            get {
                return ResourceManager.GetString("tbTrainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        public static string tbUser {
            get {
                return ResourceManager.GetString("tbUser", resourceCulture);
            }
        }
    }
}
